title: <p align="center"> Annet Chebukati </p>

logo: "/images/mlogo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/annet-chebukati-nasimiyu7/">LinkedIn</a> |
  <a href="https://github.com/Annet-Chebukati">GitHub</a>
  </p>
  
  <p align="justify">
  Data Science & AI Professional | Data Analyst | Financial Analyst | Certified FMVA® & BIDA™ | I leverage data to drive business insights, improve financial performance, and enhance predictive models
  <br><br>
  I am currently a Data Science Apprentice at Flit Inc.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-3GQE97190N # Google Analytics tracking ID
